//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Rsdn.Editor.Properties.Resources.get_ResourceManager():System.Resources.ResourceM" +
    "anager")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Rsdn.Editor.Properties.Resources.get_Culture():System.Globalization.CultureInfo")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Rsdn.Editor.Properties.Resources.set_Culture(System.Globalization.CultureInfo):Vo" +
    "id")]

namespace Rsdn.Editor.Properties {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rsdn.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Biggrin {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Biggrin", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap BrokenImg {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("BrokenImg", resourceCulture)));
            }
        }
        
        internal static byte[] InversedArrow {
            get {
                return ((byte[])(ResourceManager.GetObject("InversedArrow", resourceCulture)));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Shortcuts&gt;
        ///	&lt;!-- Навигация по тексту --&gt;
        ///	&lt;Shortcut Key=&quot;Up&quot;                      Action=&quot;CaretViewLineUp&quot;/&gt;
        ///	&lt;Shortcut Key=&quot;Down&quot;                    Action=&quot;CaretViewLineDow&quot;/&gt;
        ///	&lt;Shortcut Key=&quot;Shift | Up&quot;              Action=&quot;CaretViewLineUpExten&quot;/&gt;
        ///	&lt;Shortcut Key=&quot;Shift | Down&quot;            Action=&quot;CaretViewLineDownExten&quot;/&gt;
        ///	&lt;Shortcut Key=&quot;Home&quot;                    Action=&quot;CaretViewLineHom&quot;/&gt;
        ///	&lt;Shortcut Key=&quot;End&quot;                     Action=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeyboardShortcutsMap {
            get {
                return ResourceManager.GetString("KeyboardShortcutsMap", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Lol {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Lol", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap Smile {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Smile", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap Super {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Super", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap Xz {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Xz", resourceCulture)));
            }
        }
    }
}
