#ifndef A3D_SCENE_DEFINITIONS_INC
#define A3D_SCENE_DEFINITIONS_INC

#define SCENE_MODEL_MAX_COUNT		256
#define SCENE_LAND_MAX_COUNT		128
#define SCENE_PS_MAX_COUNT			512
#define SCENE_RS_MAX_COUNT			512
#define SCENE_EFFECT_MAX_COUNT		256
#define SCENE_TEXTURE_MAX_COUNT		2048
#define SCENE_FONT_MAX_COUNT		128
#define SCENE_SOUND_MAX_COUNT		512
#define SCENE_LIGHT_MAX_COUNT		2048
#define SCENE_MODEL_REF_MAX_COUNT	1024

#endif